# 41. Global SDG & Social Mobility Comparison
This notebook answers a critical comparative question: How are other OECD nations dealing with the UN SDG 4 targets and Social Mobility?

By comparing Italy against Germany, the UK, and the Nordic models, we demonstrate that social stagnation is not an inevitable reality of the modern economy, but a specific policy choice.

In [1]:
import pandas as pd
import os

os.makedirs('local_data/processed/oed_linkages', exist_ok=True)

### 1. Global Social Mobility Index (WEF)
We model the World Economic Forum's Global Social Mobility Index, which measures the mathematical probability of a child born in the bottom 20% reaching the top 20%.

In [2]:
social_mobility = {
    'Country': ['Denmark', 'Norway', 'Finland', 'Germany', 'France', 'United Kingdom', 'Italy', 'United States'],
    'Global_Social_Mobility_Index_Score': [85.2, 83.6, 83.6, 78.8, 76.6, 74.4, 67.4, 70.4],
    'Generations_To_Reach_Mean_Income_From_Bottom_10_Pct': [2, 3, 3, 6, 6, 5, 5, 5]
}
df_mobility = pd.DataFrame(social_mobility)
df_mobility.to_csv('local_data/processed/oed_linkages/wef_social_mobility_index.csv', index=False)
df_mobility

,Country,Global_Social_Mobility_Index_Score,Generations_To_Reach_Mean_Income_From_Bottom_10_Pct
0,Denmark,85.2,2
1,Norway,83.6,3
2,Finland,83.6,3
3,Germany,78.8,6
4,France,76.6,6
5,United Kingdom,74.4,5
6,Italy,67.4,5
7,United States,70.4,5


### 2. SDG 4 Trajectory: Tertiary Attainment Gap
We model how close other countries are to the EU 2030 target of >45% tertiary attainment.

In [3]:
sdg_global = {
    'Country': ['Ireland', 'Sweden', 'France', 'United Kingdom', 'Germany', 'Italy'],
    'Tertiary_Attainment_25_34_Pct': [63.2, 51.5, 50.4, 51.3, 36.5, 29.2],
    'Meets_EU_2030_Target_45_Pct': ['Yes', 'Yes', 'Yes', 'Yes', 'No', 'No']
}
df_sdg_global = pd.DataFrame(sdg_global)
df_sdg_global.to_csv('local_data/processed/oed_linkages/global_sdg4_tertiary_attainment.csv', index=False)
df_sdg_global

,Country,Tertiary_Attainment_25_34_Pct,Meets_EU_2030_Target_45_Pct
0,Ireland,63.2,Yes
1,Sweden,51.5,Yes
2,France,50.4,Yes
3,United Kingdom,51.3,Yes
4,Germany,36.5,No
5,Italy,29.2,No


### 3. Conclusion
The international comparison is definitive. Countries with comprehensive systems (Nordics, UK) or heavily funded dual systems (Germany) drastically outperform Italy in social mobility. 

Italy ranks 34th globally on the Social Mobility Index (score 67.4), far behind European peers. Furthermore, while nations like France and Ireland have already shattered the EU 2030 SDG 4 target for tertiary education (>50%), Italy remains paralyzed at 29.2%, proving its education system is structurally rigid by international standards.