import pandas as pd, pathlib
p = pathlib.Path('local_data/Incidenza dei giovani Neet - Titolo di studio (_) (IT1,172_931_DF_DCCV_NEET1_8,1.0).csv')
df = pd.read_csv(p, sep=',', encoding='utf-8-sig', quotechar="'", low_memory=False)
print('Shape:', df.shape)
print('EDU_LEV_HIGHEST:', df['EDU_LEV_HIGHEST'].dropna().unique()[:6])
print('Titolo di studio:', df['Titolo di studio'].dropna().unique()[:6])
print('TIME_PERIOD:', df['TIME_PERIOD'].dropna().unique()[:6])
print('AGE:', df['AGE'].dropna().unique()[:6])
print('SEX:', df['SEX'].dropna().unique()[:6])
print('Osservazione:', df['Osservazione'].dropna().unique()[:6])
print('REF_AREA:', df['REF_AREA'].dropna().unique()[:6])
print('Territorio:', df['Territorio'].dropna().unique()[:6])
